//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER
//CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER CHEATER

//ok fine here it is, and i'm sorry for calling you a cheater.

let secretArray = [
    "it",
    "unfinished",
    "iamacheater",
    "youtube"
]
var currentText = ""

function checkSecrets() {
    currentText = document.getElementById("input").value;
    let textValue = currentText.toLowerCase().replaceAll(' ', '')
    //console.log(textValue)
    for (let i = 0; i < secretArray.length; i++){
        if (textValue == secretArray[i]) {
            if (secretArray[i] == secretArray[0]) {//it
                newSecretDialog("The Keymaster","You cannot have <span style='color:lime'>it</span>.", "../../dialog/dialogIcon_002-uhd.png", "removeDialog()")
            }
            if (secretArray[i] == secretArray[1]) {//unfinished
                if (document.cookie.includes('secretLevel=true')) {

                } else {
                    document.cookie = "secretLevel=true; expires= Wed,01 Jan, 3000 12:00:00 UTC; path=/; SameSite=none; Secure";
                    newSecretDialog("OLIVER427","Hey, I got other things to do.", "../../dialog/dialogIcon_100-uhd.png", "removeDialog()")
                }
            }
            if (secretArray[i] == secretArray[2]) {//cheater cheater
                newSecretDialog("The Keymaster","Congrats on looking at the source code, I mean <span style='color:lime'>it</span> IS on GitHub.", "../../dialog/dialogIcon_002-uhd.png", "removeDialog()")
            }
            if (secretArray[i] == secretArray[3]) {//YOU TUUUBE
                newSecretDialog("The Keymaster","What is a <span style='color:red'>\"YouTube\"</span> ", "../../dialog/dialogIcon_002-uhd.png", "removeDialog()")
            }
        }
    }
}